---
# numero di db che compongono il cluster galera (>= 3)
db_num: 3
# numero di webservice / gluster server (>=3)
wp_num: 3 
# cpu per vm
vm_cpu: 1
# ram per vm
vm_ram: 512 
# password di root per mariadb
db_root_pwd: asdlkjasdlkj1
# nome database wordpress
wpdb_name: wpdb
# user per db wpdb_name
wpdb_user: wpu
# password utente wpbd_user per db wpdb_name
wpdb_pass: qwepoiqwepoi1
# rete su cui risiedono le macchine
vm_net: 192.168.122.0/24
# gw su vm_net
vm_net_gw: 192.168.122.1
